### ISSUE TITLE
Migrate to Google Analytics 4 (GA4)

### ISSUE THREAD

**Issue by chalin** [fluent/fluentd-website#243]
This is part of a CNCF-wide effort to upgrade project websites to GA4 since **Google has deprecated Universal Analytics** (UA). For more details, see:

- https://github.com/cncf/techdocs/issues/108, including reference to:
  - A suggested [migration process](https://github.com/cncf/techdocs/blob/main/docs/analytics.md#migrating-to-google-analytics-4), 
  which we've used to [migrate a few CNCF projects](https://docs.google.com/spreadsheets/d/1Mx4LhdI2Un-rvGMI73SlHxQH9D2HABAJclMB3dd6lnA) already.

### Tasks

- [x] Create a GA4 site tag under the **CNCF projects** account.
  The new GA4 stream measurement ID is: **`G-93T2VC0VBC`**
- [x] Main website - `UA-82811140-41`:
  - [x] [Connect] UA site tag from the GA4 site tag.
  - [x] Use [gtag.js] library to register GA4 ID - #241
  - [x] Confirm that the GA4 site tag is receiving events
  - [x] Confirm that the UA site tag, `UA-82811140-41`, is receiving events
- [ ] [docs.fluentd.org](https://docs.fluentd.org/) - `UA-181341719-4`, which CNCF doesn't currently have access to
  - [ ] [Connect] UA site tag from the GA4 site tag.
  - [ ] Use [gtag.js] library to register GA4 ID
- [ ] [docs.fluentbit.io](https://docs.fluentbit.io/) - `UA-181341719-3`, which CNCF doesn't currently have access to
  - [ ] [Connect] UA site tag from the GA4 site tag.
  - [ ] Use [gtag.js] library to register GA4 ID

### Later

- [ ] Cleanup: there are still traces in the main site pages of the old GTM ID. Those scripts should be removed.

/cc @nate-double-u @caniszczyk @fujimotos 

---

Related, background & prep-work:

- #100: apparently TD used `GTM-T7BJ3X` and the CNCF used `GTM-TFCP8WJ` though there is no trace of such a GTM ID at the CNCF.
- #234

[connect]: https://support.google.com/analytics/answer/9973999
[gtag.js]: https://developers.google.com/analytics/devguides/collection/gtagjs

**Comment by chalin** [comment]
@fujimotos @ashie - do you know if Fluentd websites are hosted on Netlify? If so, do you have access to the Netlify account, and can you grant me access as well?

**Comment by fujimotos** [comment]
CC: @ashie 

As far as I know, the official site is running on Heroku. It was set up
(at least) 5 years ago, and I don't have any access to that account.

**Comment by fujimotos** [comment]
> do you know if Fluentd websites are hosted on Netlify? If so, do you have access to the Netlify account, and can you grant me access as well?

As far as I know, the official site is running on Heroku. It was set up
(at least) 5 years ago, and I don't have any access to that account.

CC: @ashie

**Comment by chalin** [comment]
Thanks for that background information @fujimotos.
Do you have access to the analytics for the docs? (I have access to the main site's analytics property, but not the ones setup for the docs.)

**Comment by ashie** [comment]
> As far as I know, the official site is running on Heroku. It was set up
> (at least) 5 years ago, and I don't have any access to that account.

I don't have access to that account too.
We update the site via GitHub Actions in usual.
The account is held by Treasure Data, @toru-takahashi have the access.

> Do you have access to the analytics for the docs? (I have access to the main site's analytics property, but not the ones setup for the docs.)

No, I don't have it.
The repository of docs.fluent.org is here: https://github.com/fluent/fluentd-docs-gitbook
  * for fluentd v1.x: [1.0 branch](https://github.com/fluent/fluentd-docs-gitbook/tree/1.0)
  * for fluentd v0.12: [0.12 branch](https://github.com/fluent/fluentd-docs-gitbook/tree/0.12)

**Comment by toru-takahashi** [comment]
Let me check it in this week.

**Comment by chalin** [comment]
@toru-takahashi : thank you.

**Comment by toru-takahashi** [comment]
@chalin Hi, I've checked the ga ID. But, it is not owned by Treasure Data.
As the following commit said, it seems the Google Analayts Tag scripts from
the one used by Treasure Data to CNCF.
https://github.com/fluent/fluentd-website/commit/8bb91afc644c265c9cb239e4cfec249a67e093ee

Could you check who own the ga id?

**Comment by chalin** [comment]
Thanks for getting back to me @toru-takahashi. We're all set for the main website. My questions now pertain to the docs subdomain:

- https://github.com/fluent/fluentd-docs-gitbook/issues/437

I'll comment further in that issue.
